In [17]:
import pandas as pd
import numpy as np

ipl_ball_ball = pd.read_csv("ipl_ball_ball.csv", low_memory=False)
ipl_matches = pd.read_csv("ipl_matches.csv")

ipl_ball_ball.shape, ipl_matches.shape

((295732, 38), (1243, 32))

In [18]:
ipl_ball_ball.info()
ipl_matches.info()

display(ipl_ball_ball.head())
display(ipl_matches.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 38 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   match_id            295732 non-null  int64
 1   season              295732 non-null  int64
 2   date                295732 non-null  object
 3   venue               295732 non-null  object
 4   innings             295732 non-null  int64
 5   is_super_over       295732 non-null  bool
 6   batting_team        295732 non-null  object
 7   bowling_team        295732 non-null  object
 8   over                295732 non-null  int64
 9   ball                295732 non-null  int64
 10  delivery_in_over    295732 non-null  int64
 11  phase               295732 non-null  object
 12  batter              295732 non-null  object
 13  non_striker         295732 non-null  object
 14  bowler              295732 non-null  object
 15  batter_runs         295732 non-null  int64
 16  extra_runs          295732 non-null  int64
 17  total_runs          295732 non-null  int64
 18  extra_type          16227 non-null   object
 19  is_legal_ball       295732 non-null  bool
 20  is_four             295732 non-null  bool
 21  is_six              295732 non-null  bool
 22  is_dot              295732 non-null  bool
 23  is_wicket           295732 non-null  bool
 24  player_out          14705 non-null   object
 25  dismissal_kind      14705 non-null   object
 26  fielders            10721 non-null   object
 27  bowler_wicket       295732 non-null  bool
 28  team_score          295732 non-null  int64
 29  team_wickets        295732 non-null  int64
 30  legal_balls_bowled  295732 non-null  int64
 31  current_run_rate    295567 non-null  float64
 32  target              142303 non-null  float64
 33  runs_needed         142303 non-null  float64
 34  balls_left          142303 non-null  float64
 35  required_run_rate   141819 non-null  float64
 36  review_by           990 non-null     object
 37  review_decision     990 non-null     object
dtypes: bool(7), float64(5), int64(12), object(14)
memory usage: 71.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                1243 non-null   int64
 1   season                  1243 non-null   int64
 2   date                    1243 non-null   object
 3   match_number            1243 non-null   int64
 4   stage                   1243 non-null   object
 5   city                    1243 non-null   object
 6   venue                   1243 non-null   object
 7   country                 1243 non-null   object
 8   team1                   1243 non-null   object
 9   team2                   1243 non-null   object
 10  toss_winner             1243 non-null   object
 11  toss_decision           1243 non-null   object
 12  batting_first           1243 non-null   object
 13  batting_second          1243 non-null   object
 14  first_innings_runs      1243 non-null   int64
 15  first_innings_wickets   1243 non-null   int64
 16  first_innings_overs     1243 non-null   float64
 17  second_innings_runs     1237 non-null   float64
 18  second_innings_wickets  1237 non-null   float64
 19  second_innings_overs    1237 non-null   float64
 20  target_runs             1237 non-null   float64
 21  target_overs            1237 non-null   float64
 22  result                  1243 non-null   object
 23  winner                  1234 non-null   object
 24  win_by_runs             558 non-null    float64
 25  win_by_wickets          660 non-null    float64
 26  method                  23 non-null     object
 27  toss_winner_won         1234 non-null   object
 28  player_of_match         1234 non-null   object
 29  umpire1                 1243 non-null   object
 30  umpire2                 1243 non-null   object
 31  impact_players          291 non-null    object
dtypes: float64(8), int64(5), object(19)
memory usage: 310.9+ KB

,match_id,season,date,venue,innings,is_super_over,batting_team,bowling_team,over,ball,...,team_score,team_wickets,legal_balls_bowled,current_run_rate,target,runs_needed,balls_left,required_run_rate,review_by,review_decision
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,1,...,1,0,1,6.0,NaN,NaN,NaN,NaN,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,2,...,1,0,2,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,3,...,2,0,2,6.0,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,3,...,2,0,3,4.0,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,4,...,2,0,4,3.0,NaN,NaN,NaN,NaN,NaN,NaN

,match_id,season,date,match_number,stage,city,venue,country,team1,team2,...,result,winner,win_by_runs,win_by_wickets,method,toss_winner_won,player_of_match,umpire1,umpire2,impact_players
0,335982,2008,2008-04-18,1,League,Bengaluru,M Chinnaswamy Stadium,India,Royal Challengers Bengaluru,Kolkata Knight Riders,...,Normal,Kolkata Knight Riders,140.0,NaN,NaN,False,BB McCullum,Asad Rauf,RE Koertzen,NaN
1,335983,2008,2008-04-19,2,League,Mohali,"Punjab Cricket Association IS Bindra Stadium, ...",India,Punjab Kings,Chennai Super Kings,...,Normal,Chennai Super Kings,33.0,NaN,NaN,True,MEK Hussey,MR Benson,SL Shastri,NaN
2,335984,2008,2008-04-19,3,League,Delhi,Arun Jaitley Stadium,India,Delhi Capitals,Rajasthan Royals,...,Normal,Delhi Capitals,NaN,9.0,NaN,False,MF Maharoof,Aleem Dar,GA Pratapkumar,NaN
3,335985,2008,2008-04-20,4,League,Mumbai,Wankhede Stadium,India,Mumbai Indians,Royal Challengers Bengaluru,...,Normal,Royal Challengers Bengaluru,NaN,5.0,NaN,False,MV Boucher,SJ Davis,DJ Harper,NaN
4,335986,2008,2008-04-20,5,League,Kolkata,Eden Gardens,India,Kolkata Knight Riders,Deccan Chargers,...,Normal,Kolkata Knight Riders,NaN,5.0,NaN,False,DJ Hussey,BF Bowden,K Hariharan,NaN

In [19]:
ipl_ball_ball.info()
ipl_matches.info()

display(ipl_ball_ball.head())
display(ipl_matches.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 38 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   match_id            295732 non-null  int64
 1   season              295732 non-null  int64
 2   date                295732 non-null  object
 3   venue               295732 non-null  object
 4   innings             295732 non-null  int64
 5   is_super_over       295732 non-null  bool
 6   batting_team        295732 non-null  object
 7   bowling_team        295732 non-null  object
 8   over                295732 non-null  int64
 9   ball                295732 non-null  int64
 10  delivery_in_over    295732 non-null  int64
 11  phase               295732 non-null  object
 12  batter              295732 non-null  object
 13  non_striker         295732 non-null  object
 14  bowler              295732 non-null  object
 15  batter_runs         295732 non-null  int64
 16  extra_runs          295732 non-null  int64
 17  total_runs          295732 non-null  int64
 18  extra_type          16227 non-null   object
 19  is_legal_ball       295732 non-null  bool
 20  is_four             295732 non-null  bool
 21  is_six              295732 non-null  bool
 22  is_dot              295732 non-null  bool
 23  is_wicket           295732 non-null  bool
 24  player_out          14705 non-null   object
 25  dismissal_kind      14705 non-null   object
 26  fielders            10721 non-null   object
 27  bowler_wicket       295732 non-null  bool
 28  team_score          295732 non-null  int64
 29  team_wickets        295732 non-null  int64
 30  legal_balls_bowled  295732 non-null  int64
 31  current_run_rate    295567 non-null  float64
 32  target              142303 non-null  float64
 33  runs_needed         142303 non-null  float64
 34  balls_left          142303 non-null  float64
 35  required_run_rate   141819 non-null  float64
 36  review_by           990 non-null     object
 37  review_decision     990 non-null     object
dtypes: bool(7), float64(5), int64(12), object(14)
memory usage: 71.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                1243 non-null   int64
 1   season                  1243 non-null   int64
 2   date                    1243 non-null   object
 3   match_number            1243 non-null   int64
 4   stage                   1243 non-null   object
 5   city                    1243 non-null   object
 6   venue                   1243 non-null   object
 7   country                 1243 non-null   object
 8   team1                   1243 non-null   object
 9   team2                   1243 non-null   object
 10  toss_winner             1243 non-null   object
 11  toss_decision           1243 non-null   object
 12  batting_first           1243 non-null   object
 13  batting_second          1243 non-null   object
 14  first_innings_runs      1243 non-null   int64
 15  first_innings_wickets   1243 non-null   int64
 16  first_innings_overs     1243 non-null   float64
 17  second_innings_runs     1237 non-null   float64
 18  second_innings_wickets  1237 non-null   float64
 19  second_innings_overs    1237 non-null   float64
 20  target_runs             1237 non-null   float64
 21  target_overs            1237 non-null   float64
 22  result                  1243 non-null   object
 23  winner                  1234 non-null   object
 24  win_by_runs             558 non-null    float64
 25  win_by_wickets          660 non-null    float64
 26  method                  23 non-null     object
 27  toss_winner_won         1234 non-null   object
 28  player_of_match         1234 non-null   object
 29  umpire1                 1243 non-null   object
 30  umpire2                 1243 non-null   object
 31  impact_players          291 non-null    object
dtypes: float64(8), int64(5), object(19)
memory usage: 310.9+ KB

,match_id,season,date,venue,innings,is_super_over,batting_team,bowling_team,over,ball,...,team_score,team_wickets,legal_balls_bowled,current_run_rate,target,runs_needed,balls_left,required_run_rate,review_by,review_decision
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,1,...,1,0,1,6.0,NaN,NaN,NaN,NaN,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,2,...,1,0,2,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,3,...,2,0,2,6.0,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,3,...,2,0,3,4.0,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,False,Kolkata Knight Riders,Royal Challengers Bengaluru,1,4,...,2,0,4,3.0,NaN,NaN,NaN,NaN,NaN,NaN

,match_id,season,date,match_number,stage,city,venue,country,team1,team2,...,result,winner,win_by_runs,win_by_wickets,method,toss_winner_won,player_of_match,umpire1,umpire2,impact_players
0,335982,2008,2008-04-18,1,League,Bengaluru,M Chinnaswamy Stadium,India,Royal Challengers Bengaluru,Kolkata Knight Riders,...,Normal,Kolkata Knight Riders,140.0,NaN,NaN,False,BB McCullum,Asad Rauf,RE Koertzen,NaN
1,335983,2008,2008-04-19,2,League,Mohali,"Punjab Cricket Association IS Bindra Stadium, ...",India,Punjab Kings,Chennai Super Kings,...,Normal,Chennai Super Kings,33.0,NaN,NaN,True,MEK Hussey,MR Benson,SL Shastri,NaN
2,335984,2008,2008-04-19,3,League,Delhi,Arun Jaitley Stadium,India,Delhi Capitals,Rajasthan Royals,...,Normal,Delhi Capitals,NaN,9.0,NaN,False,MF Maharoof,Aleem Dar,GA Pratapkumar,NaN
3,335985,2008,2008-04-20,4,League,Mumbai,Wankhede Stadium,India,Mumbai Indians,Royal Challengers Bengaluru,...,Normal,Royal Challengers Bengaluru,NaN,5.0,NaN,False,MV Boucher,SJ Davis,DJ Harper,NaN
4,335986,2008,2008-04-20,5,League,Kolkata,Eden Gardens,India,Kolkata Knight Riders,Deccan Chargers,...,Normal,Kolkata Knight Riders,NaN,5.0,NaN,False,DJ Hussey,BF Bowden,K Hariharan,NaN

In [20]:
ml_data = ipl_ball_ball[
    (ipl_ball_ball["innings"] == 1) &
    (~ipl_ball_ball["is_super_over"])
].copy()

ml_data = ml_data.sort_values(
    ["match_id", "over", "delivery_in_over"],
    kind="stable"
).reset_index(drop=True)

valid_matches = ipl_matches.loc[
    (ipl_matches["result"] == "Normal") &
    (ipl_matches["method"].isna()) &
    (ipl_matches["first_innings_runs"].notna()),
    ["match_id", "first_innings_runs", "date"]
].drop_duplicates("match_id")

ml_data = ml_data.merge(
    valid_matches,
    on="match_id",
    how="inner",
    suffixes=("", "_match")
).rename(columns={"first_innings_runs": "final_score"})

ml_data.shape

(147938, 40)

In [21]:
df = ml_data.copy()

checkpoints = (
    df[df["legal_balls_bowled"].between(30, 114)]
    .sort_values(["match_id", "over", "delivery_in_over"], kind="stable")
    .drop_duplicates(["match_id", "legal_balls_bowled"], keep="last")
    .copy()
)

checkpoints = checkpoints[
    checkpoints["legal_balls_bowled"] % 6 == 0
].copy()

checkpoints["current_score"] = checkpoints["team_score"]
checkpoints["wickets_lost"] = checkpoints["team_wickets"]
checkpoints["overs_completed"] = checkpoints["legal_balls_bowled"] / 6
checkpoints["overs_remaining"] = 20 - checkpoints["overs_completed"]

checkpoints["current_run_rate"] = (
    checkpoints["current_score"] / checkpoints["overs_completed"]
)

history = df[
    ["match_id", "legal_balls_bowled", "team_score", "team_wickets"]
].drop_duplicates(["match_id", "legal_balls_bowled"], keep="last").copy()

history["legal_balls_bowled"] += 30

history = history.rename(columns={
    "team_score": "score_5_overs_ago",
    "team_wickets": "wickets_5_overs_ago"
})

checkpoints = checkpoints.merge(
    history,
    on=["match_id", "legal_balls_bowled"],
    how="left"
)

checkpoints["last_5_over_runs"] = (
    checkpoints["current_score"] -
    checkpoints["score_5_overs_ago"].fillna(0)
)

checkpoints["last_5_over_wickets"] = (
    checkpoints["wickets_lost"] -
    checkpoints["wickets_5_overs_ago"].fillna(0)
)

features = [
    "match_id", "season", "date",
    "batting_team", "bowling_team",
    "current_score", "wickets_lost",
    "overs_completed", "overs_remaining",
    "current_run_rate", "last_5_over_runs",
    "last_5_over_wickets", "final_score"
]

model_df = checkpoints[features].copy()

display(model_df.head())

,match_id,season,date,batting_team,bowling_team,current_score,wickets_lost,overs_completed,overs_remaining,current_run_rate,last_5_over_runs,last_5_over_wickets,final_score
0,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,60,0,5.0,15.0,12.000000,60.0,0.0,222
1,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,61,1,6.0,14.0,10.166667,58.0,1.0,222
2,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,68,1,7.0,13.0,9.714286,47.0,1.0,222
3,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,73,1,8.0,12.0,9.125000,41.0,1.0,222
4,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,77,1,9.0,11.0,8.555556,27.0,1.0,222

In [22]:
df = ml_data.sort_values(
    ["match_id", "over", "delivery_in_over"],
    kind="stable"
).copy()

states = df.drop_duplicates(
    ["match_id", "legal_balls_bowled"],
    keep="last"
).copy()

checkpoints = states[
    states["legal_balls_bowled"].between(30, 114)
    & states["legal_balls_bowled"].mod(6).eq(0)
].copy()

previous = states[
    ["match_id", "legal_balls_bowled", "team_score", "team_wickets"]
].copy()

previous["legal_balls_bowled"] += 30

previous = previous.rename(columns={
    "team_score": "previous_score",
    "team_wickets": "previous_wickets"
})

checkpoints = checkpoints.merge(
    previous,
    on=["match_id", "legal_balls_bowled"],
    how="left",
    validate="one_to_one"
)

checkpoints["current_score"] = checkpoints["team_score"]
checkpoints["wickets_lost"] = checkpoints["team_wickets"]
checkpoints["overs_completed"] = checkpoints["legal_balls_bowled"] / 6
checkpoints["overs_remaining"] = 20 - checkpoints["overs_completed"]

checkpoints["current_run_rate"] = (
    checkpoints["current_score"] / checkpoints["overs_completed"]
)

checkpoints["last_5_over_runs"] = (
    checkpoints["current_score"] - checkpoints["previous_score"].fillna(0)
)

checkpoints["last_5_over_wickets"] = (
    checkpoints["wickets_lost"] - checkpoints["previous_wickets"].fillna(0)
)

model_df = checkpoints[features].copy()

display(model_df.head())

,match_id,season,date,batting_team,bowling_team,current_score,wickets_lost,overs_completed,overs_remaining,current_run_rate,last_5_over_runs,last_5_over_wickets,final_score
0,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,60,0,5.0,15.0,12.000000,60.0,0.0,222
1,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,61,1,6.0,14.0,10.166667,58.0,1.0,222
2,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,68,1,7.0,13.0,9.714286,47.0,1.0,222
3,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,73,1,8.0,12.0,9.125000,41.0,1.0,222
4,335982,2008,2008-04-18,Kolkata Knight Riders,Royal Challengers Bengaluru,77,1,9.0,11.0,8.555556,27.0,1.0,222

In [23]:
eligible_matches = ipl_matches.loc[
    (ipl_matches["result"] == "Normal") &
    (ipl_matches["method"].isna()) &
    (
        (ipl_matches["first_innings_overs"] >= 19.5) |
        (ipl_matches["first_innings_wickets"] == 10)
    ),
    "match_id"
].unique()

model_df = model_df[
    model_df["match_id"].isin(eligible_matches)
].copy()

model_df["date"] = pd.to_datetime(model_df["date"], errors="coerce")

match_order = (
    model_df[["match_id", "date"]]
    .drop_duplicates("match_id")
    .sort_values(["date", "match_id"])
)

split_index = int(len(match_order) * 0.8)

train_ids = match_order.iloc[:split_index]["match_id"]
test_ids = match_order.iloc[split_index:]["match_id"]

train_df = model_df[model_df["match_id"].isin(train_ids)].copy()
test_df = model_df[model_df["match_id"].isin(test_ids)].copy()

feature_columns = [
    "batting_team",
    "bowling_team",
    "current_score",
    "wickets_lost",
    "overs_completed",
    "overs_remaining",
    "current_run_rate",
    "last_5_over_runs",
    "last_5_over_wickets"
]

X_train = train_df[feature_columns]
X_test = test_df[feature_columns]

y_train = train_df["final_score"]
y_test = test_df["final_score"]

train_df.shape, test_df.shape

((14170, 13), (3533, 13))

In [24]:

from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

categorical_features = ["batting_team", "bowling_team"]

numerical_features = [
    col for col in feature_columns
    if col not in categorical_features
]

preprocessor = ColumnTransformer([
    ("teams", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ("numerical", "passthrough", numerical_features)
])

rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=200,
        max_depth=15,
        min_samples_leaf=3,
        random_state=42,
        n_jobs=-1
    ))
])

rf_pipeline.fit(X_train, y_train)

rf_predictions = rf_pipeline.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
rf_r2 = r2_score(y_test, rf_predictions)

rf_metrics = pd.DataFrame({
    "MAE": [rf_mae],
    "RMSE": [rf_rmse],
    "R2": [rf_r2]
}).round(4)

display(rf_metrics)

results_df = test_df[
    [
        "match_id", "season", "batting_team",
        "bowling_team", "overs_completed",
        "current_score", "final_score"
    ]
].copy()

results_df["predicted_score"] = rf_predictions
results_df["absolute_error"] = (
    results_df["final_score"] - results_df["predicted_score"]
).abs()

display(results_df.head(10))

       MAE     RMSE      R2
0  16.3562  21.9031  0.6222

,match_id,season,batting_team,bowling_team,overs_completed,current_score,final_score,predicted_score,absolute_error
14233,1359518,2023,Delhi Capitals,Gujarat Titans,5.0,23,130,98.990549,31.009451
14234,1359518,2023,Delhi Capitals,Gujarat Titans,6.0,28,130,99.304696,30.695304
14235,1359518,2023,Delhi Capitals,Gujarat Titans,7.0,32,130,99.347821,30.652179
14236,1359518,2023,Delhi Capitals,Gujarat Titans,8.0,40,130,117.415805,12.584195
14237,1359518,2023,Delhi Capitals,Gujarat Titans,9.0,44,130,114.950530,15.049470
14238,1359518,2023,Delhi Capitals,Gujarat Titans,10.0,54,130,119.863405,10.136595
14239,1359518,2023,Delhi Capitals,Gujarat Titans,11.0,58,130,113.981632,16.018368
14240,1359518,2023,Delhi Capitals,Gujarat Titans,12.0,61,130,116.584432,13.415568
14241,1359518,2023,Delhi Capitals,Gujarat Titans,13.0,68,130,114.810226,15.189774
14242,1359518,2023,Delhi Capitals,Gujarat Titans,14.0,73,130,109.548464,20.451536

In [12]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Existing test predictions
evaluation_df = results_df.copy()

# Simple baseline:
# Project the current run rate over 20 overs
evaluation_df["baseline_score"] = (
    evaluation_df["current_score"] /
    evaluation_df["overs_completed"] * 20
)

# Prediction must not be below runs already scored
evaluation_df["baseline_score"] = np.maximum(
    evaluation_df["baseline_score"],
    evaluation_df["current_score"]
)

evaluation_df["rf_prediction"] = np.maximum(
    evaluation_df["predicted_score"],
    evaluation_df["current_score"]
)

# Compare across innings checkpoints
records = []

for over in [5, 8, 10, 12, 15, 18, 19]:
    subset = evaluation_df[
        evaluation_df["overs_completed"] == over
    ]

    if subset.empty:
        continue

    records.append({
        "Over": over,
        "Matches": len(subset),
        "RF_MAE": mean_absolute_error(
            subset["final_score"],
            subset["rf_prediction"]
        ),
        "Baseline_MAE": mean_absolute_error(
            subset["final_score"],
            subset["baseline_score"]
        ),
        "RF_RMSE": np.sqrt(mean_squared_error(
            subset["final_score"],
            subset["rf_prediction"]
        ))
    })

phase_results = pd.DataFrame(records).round(2)

display(phase_results)

print("\nOVERALL COMPARISON")
print(
    "Random Forest MAE:",
    round(mean_absolute_error(
        evaluation_df["final_score"],
        evaluation_df["rf_prediction"]
    ), 2)
)
print(
    "Run-rate baseline MAE:",
    round(mean_absolute_error(
        evaluation_df["final_score"],
        evaluation_df["baseline_score"]
    ), 2)
)

   Over  Matches  RF_MAE  Baseline_MAE  RF_RMSE
0     5      237   27.00         33.07    33.28
1     8      237   22.36         25.93    27.56
2    10      237   19.17         22.43    23.92
3    12      237   15.56         19.12    19.91
4    15      236   11.78         13.87    15.35
5    18      231    8.00          7.83    10.67
6    19      228    5.70          5.25     7.23

OVERALL COMPARISON
Random Forest MAE: 16.31
Run-rate baseline MAE: 19.18

In [25]:

from sklearn.ensemble import HistGradientBoostingRegressor

gb_preprocessor = ColumnTransformer([
    ("teams", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False
    ), categorical_features),
    ("numerical", "passthrough", numerical_features)
])

gb_pipeline = Pipeline([
    ("preprocessor", gb_preprocessor),
    ("model", HistGradientBoostingRegressor(
        max_iter=300,
        learning_rate=0.05,
        max_leaf_nodes=20,
        l2_regularization=5.0,
        random_state=42
    ))
])

gb_pipeline.fit(X_train, y_train)

gb_predictions = np.maximum(
    gb_pipeline.predict(X_test),
    X_test["current_score"].to_numpy()
)

rf_predictions = np.maximum(
    rf_predictions,
    X_test["current_score"].to_numpy()
)

baseline_predictions = (
    X_test["current_score"] / X_test["overs_completed"] * 20
)

comparison = pd.DataFrame([
    {
        "Model": name,
        "MAE": mean_absolute_error(y_test, pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, pred)),
        "R2": r2_score(y_test, pred)
    }
    for name, pred in [
        ("Random Forest", rf_predictions),
        ("Gradient Boosting", gb_predictions),
        ("Run-Rate Baseline", baseline_predictions)
    ]
]).round(3)

display(comparison.sort_values("MAE"))

               Model     MAE    RMSE     R2
1  Gradient Boosting  16.023  21.343  0.641
0      Random Forest  16.311  21.853  0.624
2  Run-Rate Baseline  19.177  25.982  0.468

In [26]:

gb_results_df = test_df[
    [
        "match_id", "season", "date",
        "batting_team", "bowling_team",
        "overs_completed", "current_score",
        "wickets_lost", "final_score"
    ]
].copy()

gb_results_df["predicted_score"] = gb_predictions

gb_results_df["absolute_error"] = (
    gb_results_df["final_score"] - gb_results_df["predicted_score"]
).abs()

gb_over_results = (
    gb_results_df
    .groupby("overs_completed")
    .agg(
        Matches=("match_id", "nunique"),
        MAE=("absolute_error", "mean"),
        RMSE=("absolute_error", lambda x: np.sqrt(np.mean(x ** 2)))
    )
    .reset_index()
    .round(2)
)

display(gb_over_results)

gb_metrics = pd.DataFrame({
    "MAE": [mean_absolute_error(y_test, gb_predictions)],
    "RMSE": [np.sqrt(mean_squared_error(y_test, gb_predictions))],
    "R2": [r2_score(y_test, gb_predictions)]
}).round(4)

display(gb_metrics)

    overs_completed  Matches    MAE   RMSE
0               5.0      237  25.95  32.10
1               6.0      237  24.70  30.32
2               7.0      237  23.12  28.39
3               8.0      237  21.73  26.83
4               9.0      237  19.71  24.87
5              10.0      237  18.24  22.91
6              11.0      237  16.30  20.62
7              12.0      237  15.39  19.46
8              13.0      237  14.43  18.15
9              14.0      237  13.12  16.79
10             15.0      236  11.80  15.52
11             16.0      235  10.86  13.92
12             17.0      233   9.93  12.69
13             18.0      231   8.22  10.65
14             19.0      228   6.10   7.59

       MAE     RMSE      R2
0  16.0226  21.3428  0.6413

In [15]:

# STEP 10: Audit match eligibility and innings lengths

audit = ipl_matches[
    ipl_matches["match_id"].isin(model_df["match_id"])
].copy()

# Cricket overs notation: 19.5 = 19 overs + 5 balls
audit["overs_notation"] = audit["first_innings_overs"]

audit["legal_balls_from_overs"] = (
    np.floor(audit["overs_notation"]).astype(int) * 6
    + np.rint(
        (audit["overs_notation"] % 1) * 10
    ).astype(int)
)

# Identify unusually short innings
audit["possibly_shortened"] = (
    (audit["legal_balls_from_overs"] < 120)
    & (audit["first_innings_wickets"] < 10)
)

print("Total selected matches:", len(audit))
print("Possibly shortened innings:",
      audit["possibly_shortened"].sum())

print("\nFirst-innings legal-ball distribution:")
print(
    audit["legal_balls_from_overs"]
    .value_counts()
    .sort_index()
    .tail(15)
)

print("\nPotentially problematic matches:")
display(
    audit.loc[
        audit["possibly_shortened"]
        ,
        [
            "match_id",
            "season",
            "first_innings_runs",
            "first_innings_wickets",
            "first_innings_overs",
            "target_overs",
            "method",
            "result"
        ]
    ].head(20)
)

print("\nInnings exceeding 120 legal balls:",
      (audit["legal_balls_from_overs"] > 120).sum())

Total selected matches: 1185
Possibly shortened innings: 2

First-innings legal-ball distribution:
legal_balls_from_overs
106       2
107       1
109       1
110       2
111       3
112       5
113       3
114       5
115       1
116       6
117       4
118       8
119      11
120    1116
121       1
Name: count, dtype: int64

Potentially problematic matches:

,match_id,season,first_innings_runs,first_innings_wickets,first_innings_overs,target_overs,method,result
5,335987,2008,166,8,19.5,20.0,NaN,Normal
179,501202,2011,112,8,19.5,20.0,NaN,Normal

Innings exceeding 120 legal balls: 1

In [27]:

invalid_match_ids = audit.loc[
    audit["possibly_shortened"] |
    (audit["legal_balls_from_overs"] > 120),
    "match_id"
].unique()

final_model_df = model_df[
    ~model_df["match_id"].isin(invalid_match_ids)
].copy()

match_order = (
    final_model_df[["match_id", "date"]]
    .drop_duplicates("match_id")
    .sort_values(["date", "match_id"])
)

split_index = int(len(match_order) * 0.8)

train_ids = match_order.iloc[:split_index]["match_id"]
test_ids = match_order.iloc[split_index:]["match_id"]

train_df = final_model_df[
    final_model_df["match_id"].isin(train_ids)
].copy()

test_df = final_model_df[
    final_model_df["match_id"].isin(test_ids)
].copy()

X_train = train_df[feature_columns]
X_test = test_df[feature_columns]

y_train = train_df["final_score"]
y_test = test_df["final_score"]

gb_pipeline.fit(X_train, y_train)

gb_predictions = np.maximum(
    gb_pipeline.predict(X_test),
    X_test["current_score"].to_numpy()
)

final_mae = mean_absolute_error(y_test, gb_predictions)
final_rmse = np.sqrt(mean_squared_error(y_test, gb_predictions))
final_r2 = r2_score(y_test, gb_predictions)

final_metrics = pd.DataFrame({
    "MAE": [final_mae],
    "RMSE": [final_rmse],
    "R2": [final_r2]
}).round(4)

display(final_metrics)

       MAE     RMSE     R2
0  15.8275  21.2609  0.644

In [28]:

import joblib
from pathlib import Path

output_dir = Path("IPL_Score_Prediction")
models_dir = output_dir / "models"
powerbi_dir = output_dir / "powerbi_data"

models_dir.mkdir(parents=True, exist_ok=True)
powerbi_dir.mkdir(parents=True, exist_ok=True)

joblib.dump(gb_pipeline, models_dir / "ipl_score_model.pkl")
joblib.dump(feature_columns, models_dir / "feature_columns.pkl")

prediction_df = test_df[
    [
        "match_id", "season", "date",
        "batting_team", "bowling_team",
        "overs_completed", "current_score",
        "wickets_lost", "final_score"
    ]
].copy()

prediction_df["predicted_score"] = gb_predictions

prediction_df["absolute_error"] = (
    prediction_df["final_score"] - prediction_df["predicted_score"]
).abs()

prediction_df["prediction_error"] = (
    prediction_df["predicted_score"] - prediction_df["final_score"]
)

prediction_df["match_phase"] = pd.cut(
    prediction_df["overs_completed"],
    bins=[0, 6, 15, 20],
    labels=["Powerplay", "Middle", "Death"]
)

metrics_df = pd.DataFrame([{
    "model_name": "HistGradientBoostingRegressor",
    "model_version": "1.0",
    "MAE": final_mae,
    "RMSE": final_rmse,
    "R2": final_r2,
    "training_matches": train_df["match_id"].nunique(),
    "testing_matches": test_df["match_id"].nunique()
}])

over_metrics_df = (
    prediction_df
    .groupby("overs_completed", observed=True)
    .agg(
        matches=("match_id", "nunique"),
        MAE=("absolute_error", "mean"),
        RMSE=("prediction_error", lambda x: np.sqrt(np.mean(x ** 2)))
    )
    .reset_index()
)

prediction_df.to_csv(powerbi_dir / "ipl_predictions.csv", index=False)
metrics_df.to_csv(powerbi_dir / "model_metrics.csv", index=False)
over_metrics_df.to_csv(powerbi_dir / "over_performance.csv", index=False)

display(metrics_df)

,model_name,model_version,MAE,RMSE,R2,training_matches,testing_matches
0,HistGradientBoostingRegressor,1.0,15.82745,21.260926,0.644047,945,237

In [29]:
from pathlib import Path

print("Notebook working directory:", Path.cwd())
print("ML project folder:", (Path.cwd() / "IPL_Score_Prediction").resolve())

Notebook working directory: E:\AIML\jupyterlab\ALLinONE\Machine Learning\Data Science Project\Cricket
ML project folder: E:\AIML\jupyterlab\ALLinONE\Machine Learning\Data Science Project\Cricket\IPL_Score_Prediction